### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by thibaudk**
these are the additional commits and bug fixes on 2.5.2 before "musical" branch merge

### CODE REVIEW

**Comment by jcelerier** [comment]
you should make a last commit with the latest libossia commit for the merge to work

**Comment by thibaudk** [comment]
aa yes of course ! now that it's merged 
on it now

**Comment by thibaudk** [comment]
done

**Comment by jcelerier** [comment]
damn, still conflicting ! I'll try to fix it

**Comment by thibaudk** [comment]
I am loocking at it now

**Comment by thibaudk** [comment]
it's exprtk again

**Comment by thibaudk** [comment]
i'll try something else

**Comment by jcelerier** [comment]
hmm what you can do is to go to the stable branch and run git cherry-pick first_commit_hash...last_commit_hash 

and push that

**Pull request closed without merging**
