### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./3rdparty -L desactivate,doubleclick,informations,inport,nd,normaly,pres,ro,ser,specif,splitted,te`

### CODE REVIEW

**Comment by thibaudk** [comment]
Cool ! 
This codespell looks very useful !

**Comment by jcelerier** [comment]
this is incredible aha, thanks ! i'll revie them shortly but so far everything looked good

**Comment by jcelerier** [comment]
maybe e should add this to the CI ?

**Comment by luzpaz** [comment]
An aside: here's how to add it as a github-action
https://github.com/FreeCAD/FreeCAD/commits?author=Floriansimmer  
Specifically: https://github.com/FreeCAD/FreeCAD/commit/c7cf9b25dfc6ec4fbbba8db7adfd7eb54be105fa

If the [git pollution](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame) is a problem consider creating a [`.git-blame-ignore-revs`](https://github.com/FreeCAD/FreeCAD/commit/1e4da60367a7aa52793c3cc5ee567dcc9bce91ac) file. At some point [GH may support it](https://github.com/github/feedback/discussions/5033).

**Comment by jcelerier** [comment]
rebased and merged, thanks !

**Pull request closed without merging**
