### PR TITLE
Fix: Include QUrl

### PR DESCRIPTION
**Pull request by aalex**
Fixes a build error on Pop OS 22.04.

### CODE REVIEW

**Comment by aalex** [comment]
I think there was another branch with the fix: https://github.com/ossia/score/pull/1613
And these changes might have been integrated into the main branch in another PR, anyways.

**Comment by jcelerier** [comment]
Hm I don't see it in master, let's put it there and rebase wip/pico-next on master afterwards

**Comment by jcelerier** [comment]
Argh, though this brings all the wip/pico-next commits with that... could you instead change this branch so that it is this commit 

https://github.com/ossia/score/pull/1619/commits/e58e54e74260a7216ec06be33870b7adfa3e0806

cherry-picked on top of current master ? 

(or just with the branch force-pushed as I think it would be equally fast to just redo the commit than to type git cherry-pick...)

**Comment by aalex** [comment]
It should be better, now.

**Comment by jcelerier** [comment]
thanks !

**Review by jcelerier — APPROVED** [review]

**Pull request merged**
